apiVersion: v1
kind: Service
metadata:
  labels:
    tier: msg
  name: messaging-svc
spec:
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    tier: msg
  type: ClusterIP