apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv1-claim
  namespace: default
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
