apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-flav
spec:
  containers:
  - image: nginx
    name: nginx-flav
    env:
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: keyvalcfgmap
            key: config.txt
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
